### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by ozgurcan0** [hqkirkland/Whirlpool#1]
hello, can you tell me how to install it, i have a client file. 

andthank you for doing this dude you are the only one for this

**Comment by samvermeirOISOI** [comment]
@ozgurcan0 have you found a solution?
also, how do i get a client file?

**Comment by hqkirkland** [comment]
Hey @samvermeirOISOI @ozgurcan0 

This can't be installed. Honestly, it's not useful to anyone. This is a server for my from-scratch client project, Hadley, which I'm not developing anymore. I keep the repository public to show off!

My apologies for the confusion.

Anyways, this isn't the Spineworld emulator that I originally built. Get in touch with me over Discord for that, and the client files! :)
